config/routes.rb
Rails.application.routes.draw do

  # Root routes to WelcomeController
  root 'welcome#index'

  resources :users, only: [:new, :create]
  resources :tables, only: [:new, :create, :show]
  resources :customers, only: [:create, :show]
  resources :orders, only: [:create, :destroy]
  resources :items
  resources :admin

  # Custom routes
  get '/index' => 'welcome#index', as: :log_in
  get '/users/profile' => 'users#profile', as: :profile

  post '/sessions' => 'sessions#create', as: :create_session
  delete '/sessions' => 'sessions#destroy', as: :delete_session

  put '/customers' => 'customers#update_all'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :table
  has_many :items, through: :orders
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :customers, through: :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :item
end

app/models/table.rb
class Table < ActiveRecord::Base
  belongs_to :user
  has_many :customers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tables
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @items = Item.all
    @new_item = Item.new
  end

  def show
    @item = Item.find params[:id]
  end


end # End of AdminController

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :authenticate!

  def create
    customer = Customer.create({name: Faker::Name.name, table_id: customer_params[:table_id]})
    table = Table.find customer.table_id
    table.update occupied: true, user_id: current_user.id
    redirect_to table_path(customer.table_id)
  end

  def show
    @customer = Customer.find params[:id]
    @items = Item.all
    @orders = Order.where customer_id: @customer.id
  end

  def update_all
    table = Table.find customer_params[:table_id]
    @customers = Customer.where table_id: table.id

    @customers.each do |customer|
      customer.update table_id: nil
    end

    table.update user_id: nil, occupied: false
    redirect_to profile_path
  end

  private

  def customer_params
    params.permit(:table_id)
  end

end # End of CustomersController

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    item = Item.create item_params
    redirect_to admin_index_path
  end

  def update
    item = Item.find params[:id]
    item.update item_params
    redirect_to admin_index_path
  end

  def destroy
    item = Item.find params[:id]
    item.destroy
    redirect_to admin_index_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    order = Order.create({customer_id: order_params[:customer_id], item_id: order_params[:item_id]})
    redirect_to customer_path(order.customer_id)
  end

  def destroy
    order = Order.find params[:id]
    order.destroy
    redirect_to customer_path(order_params[:customer_id])
  end

  private

  def order_params
    params.permit(:customer_id, :item_id)
  end

end # End of OrdersController

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    username = params[:username]
    password = params[:password]

    user = User.find_by username: username

    if user && user.authenticate( password )
      session[:user_id] = user.id
      redirect_to profile_path
    else
      redirect_to log_in_path
    end
  end

  # Destroy session by setting user_id to nil
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end # End of SessionsController

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  include SessionsHelper

  def new
    @table = Table.new
  end

  def create
    table = Table.create
    redirect_to profile_path
  end

  def show
    @table = Table.find params[:id]
    @customers = Customer.where table_id: @table.id

    @table_orders = []
    @sub_total = 0

    @customers.each do |customer|
      @orders = Order.where customer_id: customer.id
      @table_orders += @orders
    end
    @table_orders.each do |table_order|
      @sub_total += table_order.item.price
    end

    @tax_bill = (@sub_total * 0.08875).round(2)
    @total_bill = @tax_bill + @sub_total
  end

  private

  def table_params
    params.require(:table).permit(:user, :paid)
  end

end # End of TablesController

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # include SessionsHelper
  before_action :authenticate!, only: [:profile]

  def new
    @user = User.new
  end

  def create
    user = User.create user_params
    redirect_to log_in_path
  end

  def profile
    @user = current_user
    @tables = Table.where user_id: @user.id
    @empty_tables = Table.where occupied: false, user_id: nil
    @customers = Customer.all
    @new_table = Table.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password)
  end

end # End of UsersController

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def authenticate!
    redirect_to log_in_path unless current_user
  end

  def current_user
    @current_user = User.find session[:user_id] if session[:user_id]
  end

end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/admin/index.html.erb
<!-- Form for new menu item -->
<div class="row">
  <div class="col s12 center">
    <h3>Create Menu Item</h3>
  </div>
</div>

<%= form_for @new_item do |f| %>
<div class="row">
  <div class="input-field col s12 m8 offset-m2 l6 offset-l3">
    <%= f.label 'Item' %>
    <%= f.text_field :name %>
  </div>
</div>
<div class="row">
  <div class="input-field col s12 m8 offset-m2 l6 offset-l3">
    <%= f.label :price %>
    <%= f.number_field :price, step: 0.01 %>
  </div>
</div>
<div class="row">
  <div class="input-field col s12 m8 offset-m2 l6 offset-l3">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
</div>
<div class="row">
  <div class="col s12 m8 offset-m2 l6 offset-l3">
    <%= f.button 'Add New Item', class: "red darken-1 btn"%>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col s12">
    <h2>Current Menu</h2>
      <% @items.each_with_index do |item, index| %>
        <% if index % 2 == 0 %>
        <div class="row">
          <div class="col s6 m6 l6">
            <h4><%= link_to item.name, "/admin/#{item.id}", class: "red darken-1 white-text" %></h4>
            <h5>Price: <%= number_to_currency(item.price) %></h5>
            <h5><%= item.description %></h5>
            <%= link_to 'Delete Item', item_path(item.id), method: :delete, class: "black btn" %>
          </div>
        <% else %>
          <div class="col s6 m6 l6">
            <h4><%= link_to item.name, "/admin/#{item.id}", class: "red darken-1 white-text" %></h4>
            <h5>Price: <%= number_to_currency(item.price) %></h5>
            <h5><%= item.description %></h5>
            <%= link_to 'Delete Item', item_path(item.id), method: :delete, class: "black btn" %>
          </div>
        </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/admin/show.html.erb
<%= form_for @item do |f| %>
<div class="row">
  <div class="input-field col s12 m8 offset-m2 l6 offset-l3">
    <%= f.label 'Item' %>
    <%= f.text_field :name %>
  </div>
</div>
<div class="row">
  <div class="input-field col s12 m8 offset-m2 l6 offset-l3">
    <%= f.label :price %>
    <%= f.number_field :price, step: 0.01 %>
  </div>
</div>
<div class="row">
  <div class="input-field col s12 m8 offset-m2 l6 offset-l3">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
</div>
<div class="row">
  <div class="col s12 m8 offset-m2 l6 offset-l3">
    <%= f.button 'Edit Item', class: "red darken-1 btn" %>
  </div>
</div>
<% end %>

app/views/customers/show.html.erb
<div class="row">
  <div class="col s12 center">
    <h2>Customer: <span class="red-text text-darken-1"><%= @customer.name %></span></h2>

    <!-- Page Navigation Links -->
    <div class="page-nav row">
      <div class="col s3 m3 l3">
        <%= link_to "Back", "/tables/#{@customer.table.id}", class: "btn-large red darken-1 nav-spacing"%>
      </div>

      <div class="col s6 m6 l6">
        <h4>Current Order</h4>
      </div>
      <div class="col s2 m2 l2">

      </div>
    </div>
    <!-- End of Page Navigation -->

    <% if @orders %>
      <% @orders.each do |order| %>
      <div class="card">
        <div class="red lighten-2 card-content">
          <h4><%= order.item.name %> : $<%= order.item.price %></h4>

          <%= form_tag "/orders/#{order.id}", method: :delete do %>
            <%= hidden_field_tag :customer_id, order.customer.id %>
            <!-- <%= button_tag "#{ order.item.name } : $#{ order.item.price }", class: 'red lighten-1 btn-large' %> -->
            <%= button_tag 'Remove', class: 'red lighten-1 btn-large' %>
          <% end %>

        </div>
      </div>
      <% end %>
    <% end %>

    <h4>Menu</h4>
    <% @items.each do |item| %>
    <div class="card">
      <div class="card-content">
        <h4><%= item.name %> : $<%= item.price %></h4>

        <%= form_tag '/orders', method: :post do %>
          <%= hidden_field_tag :customer_id, @customer.id %>
          <%= hidden_field_tag :item_id, item.id %>
          <!-- <%= button_tag "#{ item.name } : $#{ item.price }", class: 'red lighten-1 btn-large' %> -->
          <%= button_tag 'Add Item', class: 'red lighten-1 btn-large' %>
        <% end %>

      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantAPP</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main" class="container grey lighten-2">
    <div class="navigation row">
      <div class="col right">
        <ul>
          <li><%= link_to "Home", profile_path, { method: :get, class: "red darken-1 btn waves-effect" } %></li>
          <% if session[:user_id] %>
          <li><%= link_to "Sign out", delete_session_path, { method: :delete, class: "red darken-1 btn waves-effect" } %></li>
          <% else %>
          <li><%= button_to "Sign in", '/', { method: :get, class: "red darken-1 btn waves-effect" } %></li>
          <% end %>
          <li><%= link_to "Sign up", '/users/new', { method: :get, class: "red darken-1 btn waves-effect" } %></li>
          <li><%= link_to "Admin", admin_index_path, { method: :get, class: "red darken-1 btn waves-effect" } %></li>
        </ul>
      </div>
    </div>

    <div class="header row">
      <div class="col s12 center">
        <h1 class="title">Order.<span class="red-text text-darken-1">ly</span></h1>
      </div>
    </div>

    <div class="container">

      <%= yield %>

    </div>
  </div>

  <footer class="container page-footer red darken-1">
    <div class="row">
      <div class="footer-stuff col s12 m12 l12">
        <h5><span class="title2">Order.<span class="white-text">ly</span></span></h5>
        <h6 class="black-text"> - Making the world a better place by revolutionizing point of sales data aggregation with fault tolerant, distributed, cloud-based acid transactions </h6>
      </div>
    </div>
    <div class="footer-copyright white-text">
      Copyright 2016 - All Rights Reserved.
    </div>
  </footer>

</body>
</html>

app/views/servers/new.html.erb
<div class="row">
  <div class="col s12 center">
    <h2>Create Account</h2>
    <%= form_for @server do |f| %>
    <div class="row">
      <div class="col s12 m6 offset-m3 l4 offset-l4">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="col s12 m6 offset-m3 l4 offset-l4">
        <%= f.label :username %>
        <%= f.text_field :username %>
      </div>
      <div class="col s12 m6 offset-m3 l4 offset-l4">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="col s12 m6 offset-m3 l4 offset-l4">
        <%= f.submit 'Create Account' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/servers/profile.html.erb
<div class="row">
  <div class="col s12 center">
    <h2>Hi, <%= @server.name %></h2>

    <form class="" action="/tables" method="post">
      <!-- <input type="hidden" name="table[server_id]" value="<%= @server.id %>"> -->
      <button type="submit" name="name" value="">Add Table</button>
    </form>

    <% @tables.each do |t| %>
    <% customers = @customers.where table_id: t.id%>
    <div class="row">
      <div class="col s12 m8 offset-m2 l6 offset-l3">
        <a class="black-text" href="/tables/<%= t.id %>">
        <div class="card">
          <div class="card-content">
            <h4>Table <%= t.id %></h4>
            <ul>
              <% customers.each do |c| %>
              <li><%= c.name %></li>
              <% end %>
            </ul>
          </div>
        </div>
        </a>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/tables/show.html.erb
<div class="row">
  <div class="col s12 center">
    <h2>Table <span class="red-text text-darken-1 border-box"><%= @table.id %></span></h2>

    <!-- Page Navigation Links -->
    <div class="page-nav row">
      <div class="col s4 m4 l4">
        <%= link_to "Back", profile_path, class: "btn-large red darken-1 nav-spacing"%>
      </div>

      <div class="col s4 m4 l4">
        <button id="view-receipt" class="btn-large red darken-1 nav-spacing" type="button" name="button">View Receipt</button>
      </div>

      <div class="col s4 m4 l4">
        <%= form_tag  '/customers', method: :post do %>
          <%= hidden_field_tag :table_id, @table.id %>
          <%= button_tag 'Add Cust', class: 'red darken-1 btn-large nav-spacing' %>
        <% end %>
      </div>
    </div>
    <!-- End of Page Navigation -->

    <!-- Receipt MODAL -->
    <div id="modal-receipt">
      <span id="close-modal">X</span>
      <% @customers.each do |customer| %>
        <h6 class="left-align white-text"><%= customer.name %></h6>
        <% orders = Order.where customer_id: customer.id %>
        <ul class="left-align">
          <% orders.each do |order| %>
            <li class="white-text"><%= order.item.name %> : $<%= order.item.price %></li>
          <% end %>
        </ul>
      <% end %>
      <h5 class="white-text">Total <%= @table_orders.length %> Item(s): <%= number_to_currency(@sub_total) %></h5>
      <h5 class="white-text">Sales Tax: <%= number_to_currency(@tax_bill) %></h5>
      <h4 class="white-text">Grand Total: <%= number_to_currency(@total_bill) %></h4>

      <!-- Pay Bill -->
      <%= form_tag '/customers', method: :put do %>
        <%= hidden_field_tag :table_id, @table.id %>
        <%= button_tag 'Pay Bill', class: 'red darken-1 btn-large' %>
      <% end %>
    </div>
    <!-- End of Receipt MODAL -->

    <% @customers.each do |customer| %>
    <a class="black-text" href="/customers/<%= customer.id %>">
    <div class="card">
      <div class="card-content hoverable">
        <h4><%= customer.name %></h4>
      </div>
    </div>
    </a>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col s12 center">
    <h2>Create Account</h2>
    <%= form_for @user do |f| %>
    <div class="row">
      <div class="input-field col s12 m6 offset-m3 l4 offset-l4">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="input-field col s12 m6 offset-m3 l4 offset-l4">
        <%= f.label :username %>
        <%= f.text_field :username %>
      </div>
      <div class="input-field col s12 m6 offset-m3 l4 offset-l4">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="col s12 m6 offset-m3 l4 offset-l4">
        <%= f.button 'Create', class: "red darken-1 btn" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="row">
  <div class="col s12 center">
    <h2>Hi, <span class="red-text text-darken-1"><%= @user.name %></span></h2>

    <%= form_tag  '/tables', method: :post do %>
      <%= button_tag 'Add Table', class: 'red darken-1 btn-large nav-spacing' %>
    <% end %>

    <div class="row">
    <!-- Render Empty Tables -->
      <div class="col s6 m6 l6">
        <h4>Open Tables:</h4>
        <% @empty_tables.each do |et| %>
        <!-- TEST CODE -->
          <a class="black-text" href="/tables/<%= et.id %>">
          <div class="card">
            <div class="card-content hoverable">
              <h4>Table <span class="red-text text-darken-1 border-box"><%= et.id %></span></h4>
            </div>
          </div>
          </a>
        <% end %>
      </div>
    <!-- End of Render Empty Tables  -->
    <!-- Render Served Tables -->
      <div class="col s6 m6 l6">
        <h4>Serving:</h4>
        <% @tables.each do |t| %>
        <% customers = @customers.where table_id: t.id%>
          <a class="black-text" href="/tables/<%= t.id %>">
          <div class="card">
            <div class="red lighten-2 card-content hoverable">
              <h4>Table <span class="white-text border-box"><%= t.id %></span></h4>
              <ul>
                <% customers.each do |c| %>
                <li><%= c.name %></li>
                <% end %>
              </ul>
            </div>
          </div>
          </a>
          <% end %>
      </div>
    <!-- End of Render Tables -->
    </div>

  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col s12 center">
    <h2>Welcome</h2>

    <%= form_tag '/sessions', method: :post do %>
    <div class="row center">
      <div class="input-field col s12 m6 offset-m3 l4 offset-l4">
        <%= label_tag :username %>
        <%= text_field_tag :username %>
      </div>
    </div>
    <div class="row center">
      <div class="input-field col s12 m6 offset-m3 l4 offset-l4">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
      </div>
    </div>
    <div class="row center">
      <div class="col s12 m6 offset-m3 l4 offset-l4">
        <!-- <%= submit_tag 'Sign in' %> -->
        <%= button_tag "Sign in", class: 'red darken-1 btn' %>
      </div>
    </div>
    <% end %>
  </div>
</div>